export const friendsArrayData = [
  {
    id: "bd7acbea-c1b1-46c2-aed5-3",
    name: "Kashyap",
    imageUrl: require("../assets/fnf/friends/1.jpg"),
    phone: "+919980027308",
    dob: "08-08-1989",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd91aa9",
    name: "Mahesh",
    imageUrl: require("../assets/fnf/friends/2.jpg"),
    phone: "+919980027308",
    dob: "08-08-1990",
    occupation: "",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "3ac68afc-c605-48d3-a4f8-fbd9",
    name: "Vishnu",
    imageUrl: require("../assets/fnf/friends/3.jpg"),
    phone: "+919980027308",
    dob: "08-08-1990",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "58694a0f-3da1-471f-bd96-145571e",
    name: "Anil",
    imageUrl: require("../assets/fnf/friends/4.jpg"),
    phone: "+919980027308",
    dob: "08-08-1991",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "58694a0f-3da1-471f-bd96-1422",
    name: "Sahil",
    imageUrl: require("../assets/fnf/friends/5.jpg"),
    phone: "+919980027308",
    dob: "08-08-1992",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "58694a0f-3da1-471f-bd96-145574",
    name: "Sandip",
    imageUrl: require("../assets/fnf/friends/6.jpg"),
    phone: "+919980027308",
    dob: "24-12-1992",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "58694a0f-3da1-423f-bd96-145571e29d75",
    name: "Bhuvana",
    imageUrl: require("../assets/fnf/friends/7.jpg"),
    phone: "+919980027308",
    dob: "08-08-1989",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "52394a0f-3da1-471f-bd96-145571e29d76",
    name: "Thrinay",
    imageUrl: require("../assets/fnf/friends/8.jpg"),
    phone: "+919980027308",
    dob: "15-04-2020",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "58694a0f-3ded-471f-bd96-145571e29d6",
    name: "Pooji",
    imageUrl: require("../assets/fnf/friends/9.jpg"),
    phone: "+919980027308",
    dob: "15-04-2020",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
  {
    id: "58694a0f-3da1-wewe1f-bd96-14557e29d76",
    name: "Bhuvi",
    imageUrl: require("../assets/fnf/friends/10.jpg"),
    phone: "+919980027308",
    dob: "15-04-2020",
    familyName: "",
    gender: "",
    maritalStatus: "",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {
      lastContacted: "10-03-2021",
      note: "regarding son birthday",
    },
  },
];

//Array of persons in the database with their data
export const personsArray = [
  {
    id: "id-ramireddy",
    name: "Rami Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "Vagalla",
    currentPlace: "Vagalla",
    occupation: "Farmer",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },

  {
    id: "id-subadhramma",
    name: "Subadhramma",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "female",
    maritalStatus: "married",
    nativePlace: "Vagalla",
    currentPlace: "Vagalla",
    occupation: "Farmer",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-vasantha",
    name: "Vasantha Kumari",
    imageUrl: require("../assets/fnf/family/7.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "female",
    maritalStatus: "married",
    nativePlace: "Kotapally",
    currentPlace: "Piler",
    occupation: "House Wife",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-mrvr",
    name: "Venkataramana Reddy",
    imageUrl: require("../assets/fnf/family/9.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "Vagalla",
    currentPlace: "Piler",
    occupation: "Lawyer",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-anil",
    name: "Anil Kumar Reddy",
    imageUrl: require("../assets/fnf/family/2.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-10-1989",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "Piler",
    currentPlace: "Hyderabad",
    occupation: "Software Engineer",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-poojitha",
    name: "Poojitha",
    imageUrl: require("../assets/fnf/family/8.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "female",
    maritalStatus: "single",
    nativePlace: "Piler",
    currentPlace: "Dallas USA",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-bhuvana",
    name: "Bhuvana Reddy",
    imageUrl: require("../assets/fnf/family/4.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "female",
    maritalStatus: "married",
    nativePlace: "Hyderabad",
    currentPlace: "Hyderabad",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-thrinay",
    name: "Thrinay Reddy",
    imageUrl: require("../assets/fnf/family/6.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "male",
    maritalStatus: "single",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-subbareddy",
    name: "Subba Reddy",
    imageUrl: require("../assets/fnf/family/10.jpg"),
    familyName: "Pallaka",
    phone: "+919980027308",
    dob: "08-08-1965",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "Appasamudram",
    currentPlace: "Hyderabad",
    occupation: "Business",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-vasanthalakshmi",
    name: "Vasantha Lakshmi",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Pallaka",
    phone: "+919980027308",
    dob: "08-08-1967",
    gender: "female",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "Hyderabad",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-madhusudhan",
    name: "Madhusudhan Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Pallaka",
    phone: "+919980027308",
    dob: "08-08-1989",
    gender: "male",
    maritalStatus: "single",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-rajagopalreddy",
    name: "Rajagopal Reddy",
    imageUrl: require("../assets/fnf/family/2.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1960",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-mamatha",
    name: "Mamatha",
    imageUrl: require("../assets/fnf/family/3.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-1965",
    gender: "female",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-karthik",
    name: "Karthik Reddy",
    imageUrl: require("../assets/fnf/family/5.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-2002",
    gender: "male",
    maritalStatus: "single",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-sai",
    name: "sai Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Mosali",
    phone: "+919980027308",
    dob: "08-08-2004",
    gender: "male",
    maritalStatus: "single",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-kcrr",
    name: "Chinna Redeppa Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Kotapalli",
    phone: "+919980027308",
    dob: "08-08-1936",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-gangulamma",
    name: "Gangulamma",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Kotapalli",
    phone: "+919980027308",
    dob: "08-08-1942",
    gender: "female",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-kvr",
    name: "Venkataramana Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Kotapalli",
    phone: "+919980027308",
    dob: "08-08-1959",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-kar",
    name: "Amarnath Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Kotapalli",
    phone: "+919980027308",
    dob: "08-08-1962",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-khr",
    name: "Harinath Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Kotapalli",
    phone: "+919980027308",
    dob: "08-08-1965",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
  {
    id: "id-kpr",
    name: "Prabhakar Reddy",
    imageUrl: require("../assets/fnf/family/1.jpg"),
    familyName: "Kotapalli",
    phone: "+919980027308",
    dob: "08-08-1972",
    gender: "male",
    maritalStatus: "married",
    nativePlace: "",
    currentPlace: "",
    occupation: "",
    facebook: "",
    instagram: "",
    twitter: "",
    linkedIn: "",
    additionalData: {},
  },
];
//PersonsArray ended

//Relationship links Array
export const relations = [
  {
    id: "r1",
    person1: "id-subadhramma",
    relationship: "husband",
    person2: "id-ramireddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },
  {
    id: "r2",
    person1: "id-ramireddy",
    relationship: "wife",
    person2: "id-subadhramma",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r3",
    person1: "id-subadhramma",
    relationship: "son",
    person2: "id-mrvr",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r4",
    person1: "id-mrvr",
    relationship: "mother",
    person2: "id-subadhramma",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r5",
    person1: "id-subadhramma",
    relationship: "son",
    person2: "id-rajagopalreddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r6",
    person1: "id-rajagopalreddy",
    relationship: "mother",
    person2: "id-subadhramma",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r7",
    person1: "id-ramireddy",
    relationship: "son",
    person2: "id-mrvr",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r8",
    person1: "id-mrvr",
    relationship: "father",
    person2: "id-ramireddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r9",
    person1: "id-ramireddy",
    relationship: "son",
    person2: "id-rajagopalreddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r10",
    person1: "id-rajagopalreddy",
    relationship: "father",
    person2: "id-ramireddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },
  {
    id: "r47",
    person1: "id-rajagopalreddy",
    relationship: "brother",
    person2: "id-mrvr",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },
  {
    id: "r48",
    person1: "id-mrvr",
    relationship: "brother",
    person2: "id-rajagopalreddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r11",
    person1: "id-vasantha",
    relationship: "husband",
    person2: "id-mrvr",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },
  {
    id: "r12",
    person1: "id-mrvr",
    relationship: "wife",
    person2: "id-vasantha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r13",
    person1: "id-vasantha",
    relationship: "son",
    person2: "id-anil",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r14",
    person1: "id-anil",
    relationship: "mother",
    person2: "id-vasantha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r15",
    person1: "id-vasantha",
    relationship: "daughter",
    person2: "id-poojitha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r16",
    person1: "id-poojitha",
    relationship: "mother",
    person2: "id-vasantha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r17",
    person1: "id-mrvr",
    relationship: "son",
    person2: "id-anil",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r18",
    person1: "id-anil",
    relationship: "father",
    person2: "id-mrvr",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r19",
    person1: "id-mrvr",
    relationship: "daughter",
    person2: "id-poojitha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r20",
    person1: "id-poojitha",
    relationship: "father",
    person2: "id-mrvr",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r21",
    person1: "id-anil",
    relationship: "sister",
    person2: "id-poojitha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r22",
    person1: "id-poojitha",
    relationship: "brother",
    person2: "id-anil",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r23",
    person1: "id-anil",
    relationship: "wife",
    person2: "id-bhuvana",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r24",
    person1: "id-bhuvana",
    relationship: "husband",
    person2: "id-anil",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r25",
    person1: "id-anil",
    relationship: "son",
    person2: "id-thrinay",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r26",
    person1: "id-thrinay",
    relationship: "father",
    person2: "id-anil",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r27",
    person1: "id-bhuvana",
    relationship: "son",
    person2: "id-thrinay",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r28",
    person1: "id-thrinay",
    relationship: "mother",
    person2: "id-bhuvana",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r29",
    person1: "id-mamatha",
    relationship: "husband",
    person2: "id-rajagopalreddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },
  {
    id: "r30",
    person1: "id-rajagopalreddy",
    relationship: "wife",
    person2: "id-mamatha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r31",
    person1: "id-mamatha",
    relationship: "son",
    person2: "id-karthik",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r32",
    person1: "id-karthik",
    relationship: "mother",
    person2: "id-mamatha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r33",
    person1: "id-mamatha",
    relationship: "son",
    person2: "id-sai",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r34",
    person1: "id-sai",
    relationship: "mother",
    person2: "id-mamatha",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r35",
    person1: "id-vasanthalakshmi",
    relationship: "husband",
    person2: "id-subbareddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },
  {
    id: "r36",
    person1: "id-subbareddy",
    relationship: "wife",
    person2: "id-vasanthalakshmi",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r37",
    person1: "id-vasanthalakshmi",
    relationship: "son",
    person2: "id-madhusudhan",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r38",
    person1: "id-madhusudhan",
    relationship: "mother",
    person2: "id-vasanthalakshmi",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r39",
    person1: "id-vasanthalakshmi",
    relationship: "daughter",
    person2: "id-bhuvana",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r40",
    person1: "id-bhuvana",
    relationship: "mother",
    person2: "id-vasanthalakshmi",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r41",
    person1: "id-subbareddy",
    relationship: "son",
    person2: "id-madhusudhan",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r42",
    person1: "id-madhusudhan",
    relationship: "father",
    person2: "id-subbareddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r43",
    person1: "id-subbareddy",
    relationship: "daughter",
    person2: "id-bhuvana",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r44",
    person1: "id-bhuvana",
    relationship: "father",
    person2: "id-subbareddy",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r45",
    person1: "id-madhusudhan",
    relationship: "sister",
    person2: "id-bhuvana",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  {
    id: "r46",
    person1: "id-bhuvana",
    relationship: "brother",
    person2: "id-madhusudhan",
    log: {
      createdBy: "",
      createdOn: "",
      lastUpdatedBy: "",
      lastUpdatedOn: "",
    },
  },

  //yet to add mother side family
];

//family tree nodes having access for anil

export const familyTree = {
  user: "id-anil",
  nodes: [
    { id: "r1", hasAccess: true },
    { id: "r2", hasAccess: true },
    { id: "r3", hasAccess: true },
    { id: "r4", hasAccess: true },
    { id: "r5", hasAccess: true },
    { id: "r6", hasAccess: true },
    { id: "r7", hasAccess: true },
    { id: "r8", hasAccess: true },
    { id: "r9", hasAccess: true },
    { id: "r10", hasAccess: true },
    { id: "r11", hasAccess: true },
    { id: "r12", hasAccess: true },
    { id: "r13", hasAccess: true },
    { id: "r14", hasAccess: true },
    { id: "r15", hasAccess: true },
    { id: "r16", hasAccess: true },
    { id: "r17", hasAccess: true },
    { id: "r18", hasAccess: true },
    { id: "r19", hasAccess: true },
    { id: "r20", hasAccess: true },
    { id: "r21", hasAccess: true },
    { id: "r22", hasAccess: true },
    { id: "r23", hasAccess: true },
    { id: "r24", hasAccess: true },
    { id: "r25", hasAccess: true },
    { id: "r26", hasAccess: true },
    { id: "r27", hasAccess: true },
    { id: "r28", hasAccess: true },
    { id: "r29", hasAccess: true },
    { id: "r30", hasAccess: true },
    { id: "r31", hasAccess: true },
    { id: "r32", hasAccess: true },
    { id: "r33", hasAccess: true },
    { id: "r34", hasAccess: true },
    { id: "r35", hasAccess: true },
    { id: "r36", hasAccess: true },
    { id: "r37", hasAccess: true },
    { id: "r38", hasAccess: true },
    { id: "r39", hasAccess: true },
    { id: "r40", hasAccess: true },
    { id: "r41", hasAccess: true },
    { id: "r42", hasAccess: true },
    { id: "r43", hasAccess: true },
    { id: "r44", hasAccess: true },
    { id: "r45", hasAccess: true },
    { id: "r46", hasAccess: true },
    { id: "r47", hasAccess: true },
    { id: "r48", hasAccess: true },
  ],
};

export default {
  friendsArrayData,
  personsArray,
  relations,
  familyTree,
};
